// <auto-generated />
namespace SymHack.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedadditionalfieldstouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedadditionalfieldstouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201811152053038_Added additional fields to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
